plugins:
  - name: solidity
  - name: hardhat
  - name: infura
  - name: vyper
  - name: etherscan

# require OpenZepplin Contracts
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.7.1
  - name: vault
    github: yearn/yearn-vaults
    version: 0.4.3

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.7.1"

ethereum:
  default_network: mainnet-fork
  mainnet:
    default_provider: infura
  mainnet_fork:
    default_provider: hardhat
