plugins:
  - name: solidity
  - name: hardhat
  - name: infura
  - name: etherscan

# require OpenZepplin Contracts
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.6.0
  - name: openzeppelin-upgradeable
    github: OpenZeppelin/openzeppelin-contracts-upgradeable
    version: 4.6.0
  - name: vault
    github: yearn/yearn-vaults
    version: 0.4.3

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.6.0"
    - "@openzeppelin-upgradeable/contracts=openzeppelin-upgradeable/v4.6.0"

ethereum:
  default_network: mainnet-fork
  mainnet:
    default_provider: infura
  mainnet_fork:
    default_provider: hardhat
