# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - yearn/yearn-vaults@0.4.3
  - openzeppelin/openzeppelin-contracts@4.7.1

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.17
    remappings:
      - "@openzeppelin/contracts=openzeppelin/openzeppelin-contracts@4.7.1/contracts"